app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => array('languages')), function () {
    Route::get('/', 'ProductsController@index');
    Route::resource('categories', 'CategoriesController');
    Route::resource('colours', 'ColoursController');
    Route::resource('products', 'ProductsController');
});

app/views/layouts/sections/mainmenu.blade.php
<div class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="{{ Request::is('products*') ? 'active' : '' }}">
                <a href="{{ URL::route('products.index') }}"><i class="fa fa-folder-open fa-fw"></i> PRODUCTOS</a>
            </li>
            <li  class="{{ Request::is('categories*') ? 'active' : '' }}">
                <a href="{{ URL::route('categories.index') }}"><i class="fa fa-tags fa-fw"></i> CATEGOR&Iacute;AS</a>
            </li>
            <li  class="{{ Request::is('colours*') ? 'active' : '' }}">
                <a href="{{ URL::route('colours.index') }}"><i class="fa fa-tint fa-fw"></i> COLORES</a>
            </li>
            <li>
                <a href="/documentacion_pdf.pdf" target="_blank"><i class="fa fa-file fa-fw"></i> DOCUMENTACI&Oacute;N</a>
            </li>
        </ul>

        <!-- /#side-menu -->
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->